// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void addProject(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.AddProject").withParams(params).execute(context);
	}
	public static void addTask(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.AddTask").withParams(params).execute(context);
	}
	public static void addTask_User(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.AddTask_User").withParams(params).execute(context);
	}
	public static void addUser(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.AddUser").withParams(params).execute(context);
	}
	public static void approveTimesheets(IContext context, myfirstmodule.proxies.Timesheet _timesheet)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Timesheet", _timesheet == null ? null : _timesheet.getMendixObject());
		Core.microflowCall("MyFirstModule.ApproveTimesheets").withParams(params).execute(context);
	}
	public static void decline(IContext context, myfirstmodule.proxies.Timesheet _timesheet)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Timesheet", _timesheet == null ? null : _timesheet.getMendixObject());
		Core.microflowCall("MyFirstModule.Decline").withParams(params).execute(context);
	}
	public static void edit_User(IContext context, myfirstmodule.proxies.Timesheet _timesheet)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Timesheet", _timesheet == null ? null : _timesheet.getMendixObject());
		Core.microflowCall("MyFirstModule.Edit_User").withParams(params).execute(context);
	}
	public static void homePage_Microflow(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.HomePage_Microflow").withParams(params).execute(context);
	}
	public static void login(IContext context, myfirstmodule.proxies.Login _login)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Login", _login == null ? null : _login.getMendixObject());
		Core.microflowCall("MyFirstModule.Login").withParams(params).execute(context);
	}
	public static boolean projectName(IContext context, myfirstmodule.proxies.Project _project)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Project", _project == null ? null : _project.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.ProjectName").withParams(params).execute(context);
	}
	public static void underReview(IContext context, myfirstmodule.proxies.Timesheet _timesheet)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Timesheet", _timesheet == null ? null : _timesheet.getMendixObject());
		Core.microflowCall("MyFirstModule.UnderReview").withParams(params).execute(context);
	}
}